### ISSUE TITLE
Themka dla potwierdzenie adres e-mail

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia.siecobywatelska.pl#37]
Należy nadpisać ```poradnia/poradnia/templates/account/email_confirm.html```

**Comment by ad-m** [comment]
![zaznaczenie_309](https://cloud.githubusercontent.com/assets/3618479/8559343/1f248b28-250c-11e5-8f95-dd1cca97d65d.png)

**Comment by mik-laj** [comment]
Close f3c8f934097338fedad501c5a7fe63ab1c459bee
