### ISSUE TITLE
Widok listy użytkowników rozszerza ekran poziomo

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/poradnia.siecobywatelska.pl#46]
![wykaz_uzytkownikow_-_2015-07-08_03 01 08](https://cloud.githubusercontent.com/assets/3618479/8560916/a609004a-251d-11e5-9a6c-f4524bd3a811.png)

**Comment by mik-laj** [comment]
Close #6b209f83ddf6f287817d0e9842d1aae3a27fec87
