### ISSUE TITLE
Mail po zarejestrowaniu sprawy - ściągnięte dwa maile Szymona

### ISSUE THREAD

**Issue by KatarzynaBatko** [watchdogpolska/poradnia.siecobywatelska.pl#64]
Drugi tak:

Temat: Informacja dotycząca zgłoszonej sprawy

Szanowna Pani/Szanowny Panie,

Informujemy, że pytanie zostało zarejestrowane w naszym systemie.

Zgodnie z dostępnym na stronie „Regulaminem poradnictwa”, odpowiedź zostanie przygotowana przez nas zespół w terminie do 10 dni. W niektórych przypadkach może to zająć więcej czasu, o czym poinformujemy. 

Z przesłanym pytaniem oraz dokumentami można zapoznać się poprzez naszą stronę internetową, która wymaga logowania http://poradnia.siecobywatelska.pl//cases/case-4. Przez stronę można przesyłać dodatkowe dokumenty i pytania.

Kontaktować się można również używając adresu sprawa-4@poradnia.siecobywatelska.pl do korespondencji w tej (konkretnej) sprawie. Dzięki temu wymiana korespondencji będzie sprawniejsza.

Z poważaniem,

Zespół Poradniczy
Sieci Obywatelskiej Watchdog Polska

---
Wspieraj działania na rzecz ochrony prawa do informacji!
http://siecobywatelska.pl/wlacz-sie-5min/#wspieraj_siec

Sieć Obywatelska Watchdog Polska
ul. Ursynowska 22/2 | 02-605 Warszawa
tel: 22 844 73 55 | fax: 22 207 24 09
www.siecobywatelska.pl
www.watchdogportal.pl
www.funduszesoleckie.pl
www.informacjapubliczna.org.pl

**Comment by KatarzynaBatko** [comment]
wyraz "drugi" z początku zignoruj. Ma być jeden mail. Przekopiowało mi się

**Comment by ad-m** [comment]
Pierwszy wiersz to jest temat. Dodałem sam. 

Dodatkowo zaznaczam, że mamy dostęp do zmiennych, które uzupełniłem, aby e-mail był trochę sprofilowany.
